### ISSUE TITLE
Twiter "Summary With Large Image" doesn't end up in the meta info...

### ISSUE THREAD

**Issue by AhoyLemon** [diesdasdigital/kirby-meta-knight#15]
I just noticed that while the UI will let you select "Summary Card With Large Image", when it gets to the output in `meta_information.php`, the twitter card is set as type summary regardless.

**Comment by jonathanmuth** [comment]
My bad. Will be fixed in the next release.

**Comment by jonathanmuth** [comment]
Fixed in 1.1.1
