### ISSUE TITLE
OG width and height meta fields...

### ISSUE THREAD

**Issue by AhoyLemon** [diesdasdigital/kirby-meta-knight#17]
In the past when I've done OpenGraph stuff, I've had validators come back and say they'd prefer the site explicitly listed the height and width of the og:image. The plugin 'does' do crops, but apparently it's still good practice to include...

```php
<meta property="og:width" content="<?= $ogimage->thumb($og_image)->toFile()->width() ?>">
<meta property="og:height" content="<?= $ogimage->thumb($og_image)->toFile()->height() ?>">
```

...as well.

**Comment by jonathanmuth** [comment]
Thanks for point this out. I will include `og:width` and `og:height` in the next release.

**Comment by jonathanmuth** [comment]
Added in 1.1.1
