### ISSUE TITLE
Option to use Site Title as title of home page

### ISSUE THREAD

**Issue by kiahreading** [diesdasdigital/kirby-meta-knight#18]
I prepend this by saying this is definitely a feature request rather than an "Issue" per se. I love the plug-in.

One thing that I do run into however is that I would love the option for the home `<title>` to default to the Site Title instead of it being `<title>Home - Site Title</title>`.

At the moment I edit the `meta_information.php` snippet to resolve this, but perhaps a config option could be implemented at some point?

**Comment by jonathanmuth** [comment]
Great idea. I will add this as a config option in an upcomming release.

**Comment by jonathanmuth** [comment]
Was added as a config option `siteTitleAsHomePageTitle` in 1.1.1

**Comment by kiahreading** [comment]
So fast! Love your work.
