### ISSUE TITLE
Canonical url different for www/non-www

### ISSUE THREAD

**Issue by iamlinkus** [diesdasdigital/kirby-meta-knight#22]
For websites that do not force redirect to a www/non-www domain, the canonical URL generated by this plugin will generate two urls:

`<link rel="canonical" href="https://example.dev/">`
`<link rel="canonical" href="https://www.example.dev/">`

I think you should mention this on the readme, so that people take it into consideration, as for the unsuspecting people who decide to use it without the force redirect, their SEO performance will be greatly downgraded, as search engines will flag their sites as having duplicate content (each page has two urls with the same content).

I've seen at least a few websites that were using this plugin and had this problem, so just wanted to mention it here. :)

**Comment by grommas** [comment]
Thanks for the hint!

**Comment by jonathanmuth** [comment]
Thanks for pointing this out. I've been working on a feature that makes sure that only one URL is being generated. It's basically a field method that ensures the canonical URL is stable not matter which URL is used to access the page. Something along those lines:

```
'canonicalUrl' => function () {
  if (option('diesdasdigital.meta-knight.canonicalURLIncludesWWW') === false) { 
    return preg_replace('/www\./', '', $this->url());
  } else {
    return preg_replace('/http(s)?:\/\/(www.)?/', 'https://www.', $this->url());
  }
}
 ```
