### ISSUE TITLE
Image url not output but its unprocessed data (->toFile() missing?)

### ISSUE THREAD

**Issue by owzim** [diesdasdigital/kirby-meta-knight#25]
Backend:

![image](https://user-images.githubusercontent.com/1720088/116435271-79898000-a84b-11eb-93f6-6f7c5ca7d5a9.png)

Generated in page file:

![image](https://user-images.githubusercontent.com/1720088/116435409-98881200-a84b-11eb-9ecd-b7bbb35b31d0.png)

Output:

```html
<meta id="schema_image" itemprop="image" content="- field-1.jpg">
```

**Comment by iamlinkus** [comment]
There's actually a PR already for this...

https://github.com/diesdasdigital/kirby-meta-knight/pull/21

**Comment by owzim** [comment]
Nice, thanks for linking.
