### ISSUE TITLE
Use page title instead of site title on homepage

### ISSUE THREAD

**Issue by S1SYPHOS** [diesdasdigital/kirby-meta-knight#32]
Hey there,

using this option, I can use the site title as homepage title:

```php
'diesdasdigital.meta-knight' => [
    'siteTitleAsHomePageTitle' => false,
],
```

.. BUT more often than not, the site title will be different from the single title I want to use for my homepage, eg I want to have a nice but short site title, so page title and site title aren't too long when used together, but on home (= index site), I wouldn't want to use this short-by-nature site title, but a nice long custom title.

I therefore suggest using the page title for more customisability instead of site title on homepage.

**Comment by S1SYPHOS** [comment]
Ah well, I accidentally pushed another commit, so they get mixed up - hope that's not a problem .. I could however commit them separately, if you insist ..

**Comment by jonathanmuth** [comment]
Hi @S1SYPHOS, thanks for raising this issue and the corresponding PR. I completely agree – the homepage title should be more configurable. I will merge your PR soon. It will be part of version 1.2.

**Comment by S1SYPHOS** [comment]
Hey @jonathanmuth, 
I thought about adding flexible `og:type` values, too and fields based on that, eg `og:type=book` would require `og:type=book:author|isbn` etc - what do you think?

**Comment by jonathanmuth** [comment]
That is an interesting idea. I wanted to keep the plugin simple in the beginning – but I can see this functionality being useful to some users. Maybe it could be a power user feature enabled via a config option. 

Would you implement this using a structure field?

**Comment by S1SYPHOS** [comment]
Well, from my experience so far, I would want to use existing fields to provide the data for these - let me think of something ;)

I'll get back to you!
