### ISSUE TITLE
Version 1.2.1 stopped working on single language pages

### ISSUE THREAD

**Issue by svenewers** [diesdasdigital/kirby-meta-knight#48]
Since updating from version 1.2 to 1.2.1 of meta knight it appears as though the plugin has stopped working on single-language Kirby instances. Every frontend page starts throwing http 500 errors after the update.

The issue appears to be in [meta_information.php:61](https://github.com/diesdasdigital/kirby-meta-knight/blob/05e619136cbb2adf5bc86e3349cc6e29bc5b1587/snippets/meta_information.php#L61) where you call `$page->url($kirby->defaultLanguage()->code())`. But since `$kirby->defaultLanguage()` is `null` on single-language Kirby instances, you're just generating a non-recoverable error here.

Here's the full log of errors I'm getting on one of my Kirby instances with 1.2.1 of meta-knight
<img width="2560" alt="Screenshot 2021-10-23 at 14 09 42" src="https://user-images.githubusercontent.com/13334117/138555463-c1f5b2cd-3625-4f78-b524-c5a252e2e06b.png">

**Comment by skyeewers** [comment]
Fixed in release 1.2.2. Thanks everyone!
