### ISSUE TITLE
Google search preview showing title as 'undefined' until the 'Title (Override)' field is edited

### ISSUE THREAD

**Issue by jamiehunterdesign** [diesdasdigital/kirby-meta-knight#8]
Fresh install of the plugin on existing page blueprints with listed pages. If I type something in the 'Title (Override)' field, then delete it, the preview correctly picks up the title of the page from the Kirby page title.

**Comment by jonathanmuth** [comment]
I'll try to reproduce this locally and report back as soon as I know more. Thanks for bringing up this issue.

**Comment by manuelvonrotz** [comment]
Maybe this is the same issue as above: I just tried out the plugin in a new Starterkit (kirby 3.5.3.1) and I can't override the title.
<img width="1481" alt="Bildschirmfoto 2021-03-12 um 12 56 40" src="https://user-images.githubusercontent.com/6112475/110937324-82bd9c80-8332-11eb-8c2b-933535e86a9d.png">

The output stays the default:
`<title>Home - Mægazine</title>`

**Comment by jonathanmuth** [comment]
Should be fixed in 1.1.1. Can you give it a try on your end and confirm that everything works as expected?
